# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/devconnect_user_service
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Hikari Connection Pool Configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariPool-1